app.controller("controladorTienda",  ["$scope", function controladorTienda($scope) {
    $scope.productos=[];
	$scope.respuesta="";
	
	$scope.obtenerTodosReales = function(){
		$scope.productos=[{id:"2",ruta:"chompa2-1.jpg",ruta2:"chompa2-2.jpg",descripcion:"Chompa exforzarse",color:"Camuflada naranja",tipo:"hombre",indumentaria:"chompa",precio:"75.000"},
				  		  {id:"3",ruta:"chompa3-1.jpg",ruta2:"chompa3-1.jpg",descripcion:"Chompa Exforzarse",color:"Gris oscuro con bordes naranjas",tipo:"hombre",indumentaria:"chompa",precio:"75.000"},
				  		  {id:"4",ruta:"chompa4-1.jpg",ruta2:"chompa4-2.jpg",descripcion:"Chompa Exforzarse",color:"Gris con bordes azules",tipo:"mujer",indumentaria:"chompa",precio:"75.000"},
				  		  {id:"5",ruta:"chompa5-1.jpg",ruta2:"chompa5-2.jpg",descripcion:"Chompa Exforzarse",color:"Camuflada azul",tipo:"mujer",indumentaria:"chompa",precio:"75.000"},
				  		  {id:"7",ruta:"chompa7-1.jpg",ruta2:"chompa7-2.jpg",descripcion:"Chompa Exforzarse",color:"Negra con bordes naranjas",tipo:"hombre",indumentaria:"chompa",precio:"75.000"},
				  		  {id:"8",ruta:"chompa8-1.jpg",ruta2:"chompa8-2.jpg",descripcion:"Chompa Exforzarse",color:"Militar",tipo:"hombre",indumentaria:"chompa",precio:"75.000"},
				  		  {id:"1",ruta:"chompa1-1.jpg",ruta2:"chompa1-2.jpg",descripcion:"Buso de cremallera",color:"Gris",tipo:"hombre",indumentaria:"chompa",precio:"70.000"},
				  		  {id:"6",ruta:"chompa6-1.jpg",ruta2:"chompa6-1.jpg",descripcion:"Buso de cremallera",color:"Negra",tipo:"hombre",indumentaria:"chompa",precio:"70.000"},
				  		  {id:"9",ruta:"sudaderaTela1-1.jpg",ruta2:"sudaderaTela1-2.jpg",descripcion:"Sudadera de tela",color:"Negra",tipo:"hombre",indumentaria:"sudadera",precio:"55.000"},
				  		  {id:"10",ruta:"esqueleto1-1.jpg",ruta2:"esqueleto1-2.jpg",descripcion:"Exqueleto Exforzarse",color:"Camuflada naranja",tipo:"hombre",indumentaria:"camisilla",precio:"35.000"},
				  		  {id:"11",ruta:"esqueleto2-1.jpg",ruta2:"esqueleto2-2.jpg",descripcion:"Exqueleto Exforzarse",color:"Azul oscuro con naranja",tipo:"hombre",indumentaria:"camisilla",precio:"35.000"},
				  		  {id:"12",ruta:"esqueleto3-1.jpg",ruta2:"esqueleto3-2.jpg",descripcion:"Exqueleto Streetworkout",color:"Azul",tipo:"hombre",indumentaria:"camisilla",precio:"30.000"},
				  		  {id:"13",ruta:"esqueleto4-1.jpg",ruta2:"esqueleto4-2.jpg",descripcion:"Exqueleto Streetworkout",color:"Verde",tipo:"hombre",indumentaria:"camisilla",precio:"30.000"},
				  		  {id:"14",ruta:"esqueleto5-1.jpg",ruta2:"esqueleto5-1.jpg",descripcion:"Exqueleto Streetworkout",color:"Naranja",tipo:"hombre",indumentaria:"camisilla",precio:"30.000"},
				  		  ];
	}
	
	$scope.obtenerTodos = function(){
        $scope.respuesta="Todos los productos";
        $scope.productos=[{ ruta:"camisetahombre1.jpg",descripcion:"camiseta para hombre azul",tipo:"hombre",indumentaria:"camiseta"},
        				  { ruta:"camisetahombre2.jpg",descripcion:"camiseta para hombre rosa",tipo:"hombre",indumentaria:"camiseta"},
        				  { ruta:"camisetahombre3.jpg",descripcion:"camiseta para hombre rosa",tipo:"hombre",indumentaria:"camiseta"},
        				  { ruta:"camisetahombre4.jpg",descripcion:"camiseta para hombre verde",tipo:"hombre",indumentaria:"camiseta"},
        				  { ruta:"camisetahombre5.jpg",descripcion:"camiseta para hombre verde",tipo:"hombre",indumentaria:"camiseta"},
        				  { ruta:"camisetamujer1.jpg",descripcion:"camiseta para mujer rosa",tipo:"mujer",indumentaria:"camiseta"},
        				  { ruta:"camisetamujer2.jpg",descripcion:"camiseta para mujer negra",tipo:"mujer",indumentaria:"camiseta"},
        				  { ruta:"camisetamujer3.jpg",descripcion:"camiseta para mujer rosa",tipo:"mujer",indumentaria:"camiseta"},
        				  { ruta:"camisetamujer4.jpg",descripcion:"camiseta para mujer negra",tipo:"mujer",indumentaria:"camiseta"},
        				  { ruta:"camisetamujer5.jpg",descripcion:"camiseta para mujer violeta",tipo:"mujer",indumentaria:"camiseta"},
        				  { ruta:"camisillahombre1.jpg",descripcion:"camisilla para hombre negra",tipo:"hombre",indumentaria:"camisilla"},
        				  { ruta:"camisillahombre2.jpg",descripcion:"camisilla para hombre blanca",tipo:"hombre",indumentaria:"camisilla"},
        				  { ruta:"camisillahombre3.jpg",descripcion:"camisilla para hombre azul",tipo:"hombre",indumentaria:"camisilla"},
        				  { ruta:"camisillahombre4.jpg",descripcion:"camisilla para hombre azul",tipo:"hombre",indumentaria:"camisilla"},
        				  { ruta:"camisillamujer1.jpg",descripcion:"camisilla para mujer gris",tipo:"mujer",indumentaria:"camisilla"},
        				  { ruta:"camisillamujer2.jpg",descripcion:"camisilla para mujer morada",tipo:"mujer",indumentaria:"camisilla"},
        				  { ruta:"camisillamujer3.jpg",descripcion:"camisilla para mujer rosa",tipo:"mujer",indumentaria:"camisilla"},
        				  { ruta:"camisillamujer4.jpg",descripcion:"camisilla para mujer negra",tipo:"mujer",indumentaria:"camisilla"},
        				  { ruta:"camisillamujer5.jpg",descripcion:"camisilla para mujer verde azul",tipo:"mujer",indumentaria:"camisilla"},
        				  { ruta:"chompahombre1.jpg",descripcion:"chompa para hombre negra",tipo:"hombre",indumentaria:"chompa"},
        				  { ruta:"chompahombre2.jpg",descripcion:"chompa para hombre amarilla",tipo:"hombre",indumentaria:"chompa"},
        				  { ruta:"chompahombre3.jpg",descripcion:"chompa para hombre negra",tipo:"hombre",indumentaria:"chompa"},
        				  { ruta:"chompahombre4.jpg",descripcion:"chompa para hombre gris-amarilla",tipo:"hombre",indumentaria:"chompa"},
        				  { ruta:"chompahombre5.jpg",descripcion:"chompa para hombre azul claro",tipo:"hombre",indumentaria:"chompa"},
        				  { ruta:"chompahombre6.jpg",descripcion:"chompa para hombre roja",tipo:"hombre",indumentaria:"chompa"},
        				  { ruta:"chompahombre7.png",descripcion:"chompa para hombre azul",tipo:"hombre",indumentaria:"chompa"},
        				  { ruta:"chompamujer1.jpg",descripcion:"chompa para mujer gris azul",tipo:"mujer",indumentaria:"chompa"},
        				  { ruta:"chompamujer2.jpg",descripcion:"chompa para mujer negra",tipo:"mujer",indumentaria:"chompa"},
        				  { ruta:"chompamujer3.jpg",descripcion:"chompa para mujer roja con morado",tipo:"mujer",indumentaria:"chompa"},
        				  { ruta:"chompamujer4.jpg",descripcion:"chompa para mujer verde azul",tipo:"mujer",indumentaria:"chompa"},
        				  { ruta:"chompamujer5.jpg",descripcion:"chompa para mujer roja",tipo:"mujer",indumentaria:"chompa"},
        				  { ruta:"chompamujer6.jpg",descripcion:"chompa para mujer azul",tipo:"mujer",indumentaria:"chompa"},
        				  { ruta:"chompamujer7.jpg",descripcion:"chompa para mujer naranja",tipo:"mujer",indumentaria:"chompa"},
        				  { ruta:"gorrahombre1.jpg",descripcion:"gorra para hombre",tipo:"hombre",indumentaria:"gorra"},
        				  { ruta:"gorrahombre2.jpg",descripcion:"gorra para hombre",tipo:"hombre",indumentaria:"gorra"},
        				  { ruta:"gorrahombre3.jpg",descripcion:"gorra para hombre",tipo:"hombre",indumentaria:"gorra"},
        				  { ruta:"gorrahombre4.jpg",descripcion:"gorra para hombre",tipo:"hombre",indumentaria:"gorra"},
        				  { ruta:"gorrahombre5.jpeg",descripcion:"gorra para hombre",tipo:"hombre",indumentaria:"gorra"},
        				  { ruta:"gorrahombre6.jpg",descripcion:"gorra para hombre",tipo:"hombre",indumentaria:"gorra"},
        				  { ruta:"gorramujer1.jpg",descripcion:"gorra para mujer",tipo:"mujer",indumentaria:"gorra"},
        				  { ruta:"gorramujer2.jpg",descripcion:"gorra para mujer",tipo:"mujer",indumentaria:"gorra"},
        				  { ruta:"gorramujer3.jpg",descripcion:"gorra para mujer",tipo:"mujer",indumentaria:"gorra"},
        				  { ruta:"gorramujer4.jpg",descripcion:"gorra para mujer",tipo:"mujer",indumentaria:"gorra"},
        				  { ruta:"gorramujer5.jpg",descripcion:"gorra para mujer",tipo:"mujer",indumentaria:"gorra"},
        				  { ruta:"gorramujer6.jpg",descripcion:"gorra para mujer",tipo:"mujer",indumentaria:"gorra"},
        				  { ruta:"gorramujer7.jpg",descripcion:"gorra para mujer",tipo:"mujer",indumentaria:"gorra"},
        				  { ruta:"gorramujer8.jpg",descripcion:"gorra para mujer",tipo:"mujer",indumentaria:"gorra"},
        				  { ruta:"gorramujer9.jpg",descripcion:"gorra para mujer",tipo:"mujer",indumentaria:"gorra"},
        				  { ruta:"leggins1.jpg",descripcion:"leggins para mujer",tipo:"mujer",indumentaria:"leggins"},
        				  { ruta:"leggins2.jpg",descripcion:"leggins para mujer",tipo:"mujer",indumentaria:"leggins"},
        				  { ruta:"leggins3.jpg",descripcion:"leggins para mujer",tipo:"mujer",indumentaria:"leggins"},
        				  { ruta:"leggins4.jpg",descripcion:"leggins para mujer",tipo:"mujer",indumentaria:"leggins"},
        				  { ruta:"leggins5.jpg",descripcion:"leggins para mujer",tipo:"mujer",indumentaria:"leggins"},
        				  { ruta:"mediashombre1.jpg",descripcion:"medias para hombre",tipo:"hombre",indumentaria:"medias"},
        				  { ruta:"mediashombre2.jpg",descripcion:"medias para hombre",tipo:"hombre",indumentaria:"medias"},
        				  { ruta:"mediashombre3.jpg",descripcion:"medias para hombre",tipo:"hombre",indumentaria:"medias"},
        				  { ruta:"mediashombre4.jpg",descripcion:"medias para hombre",tipo:"hombre",indumentaria:"medias"},
        				  { ruta:"mediashombre5.jpg",descripcion:"medias para hombre",tipo:"hombre",indumentaria:"medias"},
        				  { ruta:"mediashombre6.jpg",descripcion:"medias para hombre",tipo:"hombre",indumentaria:"medias"},
        				  { ruta:"mediashombre7.jpg",descripcion:"medias para hombre",tipo:"hombre",indumentaria:"medias"},
        				  { ruta:"mediasmujer1.jpg",descripcion:"medias para mujer",tipo:"mujer",indumentaria:"medias"},
        				  { ruta:"mediasmujer2.jpg",descripcion:"medias para mujer",tipo:"mujer",indumentaria:"medias"},
        				  { ruta:"mediasmujer3.JPG",descripcion:"medias para mujer",tipo:"mujer",indumentaria:"medias"},
        				  { ruta:"mediasmujer4.jpg",descripcion:"medias para mujer",tipo:"mujer",indumentaria:"medias"},
        				  { ruta:"mediasmujer5.jpg",descripcion:"medias para mujer",tipo:"mujer",indumentaria:"medias"},
        				  { ruta:"sudaderahombre1.JPG",descripcion:"sudadera para hombre",tipo:"hombre",indumentaria:"sudadera"},
        				  { ruta:"sudaderahombre2.jpg",descripcion:"sudadera para hombre",tipo:"hombre",indumentaria:"sudadera"},
        				  { ruta:"sudaderamujer1.jpg",descripcion:"sudadera para mujer",tipo:"mujer",indumentaria:"sudadera"},
        				  { ruta:"sudaderamujer2.jpg",descripcion:"sudadera para mujer",tipo:"mujer",indumentaria:"sudadera"},
        				  { ruta:"tenismujer1.jpg",descripcion:"tenis para mujer",tipo:"mujer",indumentaria:"tenis"},
        				  { ruta:"tenismujer2.jpg",descripcion:"tenis para mujer",tipo:"mujer",indumentaria:"tenis"},
        				  { ruta:"tenismujer3.jpg",descripcion:"tenis para mujer",tipo:"mujer",indumentaria:"tenis"},
        				  { ruta:"tenismujer4.jpg",descripcion:"tenis para mujer",tipo:"mujer",indumentaria:"tenis"},
        				  { ruta:"tenismujer5.jpg",descripcion:"tenis para mujer",tipo:"mujer",indumentaria:"tenis"},
        				  { ruta:"tenismujer6.jpg",descripcion:"tenis para mujer",tipo:"mujer",indumentaria:"tenis"},
        				  { ruta:"tenishombre1.jpg",descripcion:"tenis para hombre",tipo:"hombre",indumentaria:"tenis"},
        				  { ruta:"tenishombre2.jpg",descripcion:"tenis para hombre",tipo:"hombre",indumentaria:"tenis"},
        				  { ruta:"tenishombre3.jpg",descripcion:"tenis para hombre",tipo:"hombre",indumentaria:"tenis"},
        				  { ruta:"tenishombre4.jpg",descripcion:"tenis para hombre",tipo:"hombre",indumentaria:"tenis"},
        				  { ruta:"tenishombre5.jpg",descripcion:"tenis para hombre",tipo:"hombre",indumentaria:"tenis"}
                         ];
	}
}]);